name: 'DocEvaluator'
description: 'A tool to check whether the documentation is sufficient'
author: 'Timo Schoemaker'
inputs:
  absolute_threshold:
    description: "The global threshold when to fail"
    required: false
runs:
  using: 'node16'
  main: 'build/index.js'
  
