/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example;

public class Library {
    private NumberProperties numberProperties;

    public boolean someLibraryMethod() {
        MathStuff stuff = new MathStuff(numberProperties);
        if(numberProperties.getSign()){
            stuff.calcValue();
        }
       System.out.println(numberProperties.getSign());
       System.out.println(numberProperties.getMantissa());
       System.out.println(numberProperties.getExponent());
        return true;
    }
}
